server:
  port: 8089

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          default-label: main
          search-locations: file:D:/IdeaCloud/spring-cloud-course/config-server-local-bundle/configs/

management:
  endpoints:
    web:
      exposure:
        include: health,info
